# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import services_pb2 as services__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MathServiceStub(object):
    """========================================
    Servicio 1: Operaciones Matemáticas
    ========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/distributed_system.MathService/Add',
                request_serializer=services__pb2.MathRequest.SerializeToString,
                response_deserializer=services__pb2.MathResponse.FromString,
                _registered_method=True)
        self.Subtract = channel.unary_unary(
                '/distributed_system.MathService/Subtract',
                request_serializer=services__pb2.MathRequest.SerializeToString,
                response_deserializer=services__pb2.MathResponse.FromString,
                _registered_method=True)
        self.Multiply = channel.unary_unary(
                '/distributed_system.MathService/Multiply',
                request_serializer=services__pb2.MathRequest.SerializeToString,
                response_deserializer=services__pb2.MathResponse.FromString,
                _registered_method=True)
        self.Divide = channel.unary_unary(
                '/distributed_system.MathService/Divide',
                request_serializer=services__pb2.MathRequest.SerializeToString,
                response_deserializer=services__pb2.MathResponse.FromString,
                _registered_method=True)


class MathServiceServicer(object):
    """========================================
    Servicio 1: Operaciones Matemáticas
    ========================================
    """

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subtract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Multiply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Divide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MathServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=services__pb2.MathRequest.FromString,
                    response_serializer=services__pb2.MathResponse.SerializeToString,
            ),
            'Subtract': grpc.unary_unary_rpc_method_handler(
                    servicer.Subtract,
                    request_deserializer=services__pb2.MathRequest.FromString,
                    response_serializer=services__pb2.MathResponse.SerializeToString,
            ),
            'Multiply': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiply,
                    request_deserializer=services__pb2.MathRequest.FromString,
                    response_serializer=services__pb2.MathResponse.SerializeToString,
            ),
            'Divide': grpc.unary_unary_rpc_method_handler(
                    servicer.Divide,
                    request_deserializer=services__pb2.MathRequest.FromString,
                    response_serializer=services__pb2.MathResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_system.MathService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_system.MathService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MathService(object):
    """========================================
    Servicio 1: Operaciones Matemáticas
    ========================================
    """

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.MathService/Add',
            services__pb2.MathRequest.SerializeToString,
            services__pb2.MathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subtract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.MathService/Subtract',
            services__pb2.MathRequest.SerializeToString,
            services__pb2.MathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Multiply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.MathService/Multiply',
            services__pb2.MathRequest.SerializeToString,
            services__pb2.MathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Divide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.MathService/Divide',
            services__pb2.MathRequest.SerializeToString,
            services__pb2.MathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AverageServiceStub(object):
    """========================================
    Servicio 2: Promedio de números
    ========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateAverage = channel.unary_unary(
                '/distributed_system.AverageService/CalculateAverage',
                request_serializer=services__pb2.AverageRequest.SerializeToString,
                response_deserializer=services__pb2.AverageResponse.FromString,
                _registered_method=True)


class AverageServiceServicer(object):
    """========================================
    Servicio 2: Promedio de números
    ========================================
    """

    def CalculateAverage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AverageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateAverage': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateAverage,
                    request_deserializer=services__pb2.AverageRequest.FromString,
                    response_serializer=services__pb2.AverageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_system.AverageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_system.AverageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AverageService(object):
    """========================================
    Servicio 2: Promedio de números
    ========================================
    """

    @staticmethod
    def CalculateAverage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.AverageService/CalculateAverage',
            services__pb2.AverageRequest.SerializeToString,
            services__pb2.AverageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MatrixServiceStub(object):
    """========================================
    Servicio 3: Multiplicación de matrices
    ========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MultiplyMatrices = channel.unary_unary(
                '/distributed_system.MatrixService/MultiplyMatrices',
                request_serializer=services__pb2.MatrixRequest.SerializeToString,
                response_deserializer=services__pb2.MatrixResponse.FromString,
                _registered_method=True)


class MatrixServiceServicer(object):
    """========================================
    Servicio 3: Multiplicación de matrices
    ========================================
    """

    def MultiplyMatrices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MatrixServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MultiplyMatrices': grpc.unary_unary_rpc_method_handler(
                    servicer.MultiplyMatrices,
                    request_deserializer=services__pb2.MatrixRequest.FromString,
                    response_serializer=services__pb2.MatrixResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_system.MatrixService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_system.MatrixService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MatrixService(object):
    """========================================
    Servicio 3: Multiplicación de matrices
    ========================================
    """

    @staticmethod
    def MultiplyMatrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.MatrixService/MultiplyMatrices',
            services__pb2.MatrixRequest.SerializeToString,
            services__pb2.MatrixResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SortServiceStub(object):
    """========================================
    Servicio 4: Quick Sort
    ========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QuickSort = channel.unary_unary(
                '/distributed_system.SortService/QuickSort',
                request_serializer=services__pb2.SortRequest.SerializeToString,
                response_deserializer=services__pb2.SortResponse.FromString,
                _registered_method=True)


class SortServiceServicer(object):
    """========================================
    Servicio 4: Quick Sort
    ========================================
    """

    def QuickSort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SortServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QuickSort': grpc.unary_unary_rpc_method_handler(
                    servicer.QuickSort,
                    request_deserializer=services__pb2.SortRequest.FromString,
                    response_serializer=services__pb2.SortResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_system.SortService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_system.SortService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SortService(object):
    """========================================
    Servicio 4: Quick Sort
    ========================================
    """

    @staticmethod
    def QuickSort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.SortService/QuickSort',
            services__pb2.SortRequest.SerializeToString,
            services__pb2.SortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SearchServiceStub(object):
    """========================================
    Servicio 5: Búsqueda Lineal
    ========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LinearSearch = channel.unary_unary(
                '/distributed_system.SearchService/LinearSearch',
                request_serializer=services__pb2.SearchRequest.SerializeToString,
                response_deserializer=services__pb2.SearchResponse.FromString,
                _registered_method=True)


class SearchServiceServicer(object):
    """========================================
    Servicio 5: Búsqueda Lineal
    ========================================
    """

    def LinearSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LinearSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.LinearSearch,
                    request_deserializer=services__pb2.SearchRequest.FromString,
                    response_serializer=services__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_system.SearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_system.SearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SearchService(object):
    """========================================
    Servicio 5: Búsqueda Lineal
    ========================================
    """

    @staticmethod
    def LinearSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.SearchService/LinearSearch',
            services__pb2.SearchRequest.SerializeToString,
            services__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MessageServiceStub(object):
    """========================================
    Servicio 6: Envío de mensajes (Lamport)
    ========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/distributed_system.MessageService/SendMessage',
                request_serializer=services__pb2.MessageRequest.SerializeToString,
                response_deserializer=services__pb2.MessageResponse.FromString,
                _registered_method=True)


class MessageServiceServicer(object):
    """========================================
    Servicio 6: Envío de mensajes (Lamport)
    ========================================
    """

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=services__pb2.MessageRequest.FromString,
                    response_serializer=services__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_system.MessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_system.MessageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageService(object):
    """========================================
    Servicio 6: Envío de mensajes (Lamport)
    ========================================
    """

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.MessageService/SendMessage',
            services__pb2.MessageRequest.SerializeToString,
            services__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BroadcastServiceStub(object):
    """========================================
    Servicio 7: Broadcast (difusión)
    ========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BroadcastMessage = channel.unary_unary(
                '/distributed_system.BroadcastService/BroadcastMessage',
                request_serializer=services__pb2.BroadcastRequest.SerializeToString,
                response_deserializer=services__pb2.BroadcastResponse.FromString,
                _registered_method=True)


class BroadcastServiceServicer(object):
    """========================================
    Servicio 7: Broadcast (difusión)
    ========================================
    """

    def BroadcastMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BroadcastServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BroadcastMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastMessage,
                    request_deserializer=services__pb2.BroadcastRequest.FromString,
                    response_serializer=services__pb2.BroadcastResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_system.BroadcastService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_system.BroadcastService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BroadcastService(object):
    """========================================
    Servicio 7: Broadcast (difusión)
    ========================================
    """

    @staticmethod
    def BroadcastMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_system.BroadcastService/BroadcastMessage',
            services__pb2.BroadcastRequest.SerializeToString,
            services__pb2.BroadcastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
